/**
 * Secrets for a local instance.
 *
 * Generated by the CLI before the containers start, so `local start` knows the
 * API key and can link the directory without asking the backend for it. The
 * backend seeds ACCESS_API_KEY / ACCESS_ANON_KEY into its secret store on first
 * boot and ignores them afterwards, which is what makes a restart idempotent.
 *
 * Written once to .insforge/local.env at mode 0600 and re-read on every later
 * start — regenerating would rotate the keys out from under a running app.
 */

import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { ensureLocalDir, ensureLocalGitignore, localEnvFile } from './state.js';
import type { LocalPorts, StorageBackend } from './state.js';

export interface LocalSecrets {
  jwtSecret: string;
  encryptionKey: string;
  /** Includes the `ik_` prefix the backend expects. */
  apiKey: string;
  /** Includes the `anon_` prefix. */
  anonKey: string;
  adminUsername: string;
  adminPassword: string;
  /** Credentials for the bundled object store, when one is used. */
  storeAccessKey: string;
  storeSecretKey: string;
}

function hex(bytes: number): string {
  return randomBytes(bytes).toString('hex');
}

export function generateSecrets(): LocalSecrets {
  return {
    // 64 hex chars — comfortably over the backend's 32-character minimum.
    jwtSecret: hex(32),
    encryptionKey: hex(32),
    apiKey: `ik_${hex(20)}`,
    anonKey: `anon_${hex(20)}`,
    adminUsername: 'admin',
    adminPassword: hex(8),
    storeAccessKey: 'insforge',
    storeSecretKey: hex(16),
  };
}

const ENV_KEYS: Record<keyof LocalSecrets, string> = {
  jwtSecret: 'JWT_SECRET',
  encryptionKey: 'ENCRYPTION_KEY',
  apiKey: 'ACCESS_API_KEY',
  anonKey: 'ACCESS_ANON_KEY',
  adminUsername: 'ROOT_ADMIN_USERNAME',
  adminPassword: 'ROOT_ADMIN_PASSWORD',
  storeAccessKey: 'INSFORGE_STORE_ACCESS_KEY',
  storeSecretKey: 'INSFORGE_STORE_SECRET_KEY',
};

export function parseEnvFile(content: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    out[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return out;
}

/** Read secrets back from a previously written env file, or null if absent. */
export function readSecrets(cwd?: string): LocalSecrets | null {
  const file = localEnvFile(cwd);
  if (!existsSync(file)) return null;
  const env = parseEnvFile(readFileSync(file, 'utf-8'));
  const entries = Object.entries(ENV_KEYS) as [keyof LocalSecrets, string][];
  const secrets = {} as LocalSecrets;
  for (const [field, key] of entries) {
    const value = env[key];
    // A partial file means something truncated it. Regenerating is wrong (it
    // would rotate keys the running app holds), so surface it as "not found"
    // and let the caller refuse rather than silently half-configure compose.
    if (!value) return null;
    secrets[field] = value;
  }
  return secrets;
}

export interface EnvFileInput {
  secrets: LocalSecrets;
  ports: LocalPorts;
  storage: StorageBackend;
  stackTag: string | null;
  /** Public URL browsers use. Defaults to localhost on the app port. */
  apiUrl?: string;
}

/**
 * Render the compose `--env-file`. Ports and image tags live here too so a
 * user can inspect (or hand-run) the exact configuration the CLI used:
 *   docker compose --env-file .insforge/local.env -p <name> ps
 */
export function renderEnvFile({
  secrets,
  ports,
  storage,
  stackTag,
  apiUrl: publicUrl,
}: EnvFileInput): string {
  const apiUrl = publicUrl ?? `http://localhost:${ports.app}`;
  const lines = [
    '# Generated by `insforge local start`. Do not edit or commit.',
    '# Deleting this file loses the keys for the running instance.',
    '',
    `JWT_SECRET=${secrets.jwtSecret}`,
    `ENCRYPTION_KEY=${secrets.encryptionKey}`,
    `ACCESS_API_KEY=${secrets.apiKey}`,
    `ACCESS_ANON_KEY=${secrets.anonKey}`,
    `ROOT_ADMIN_USERNAME=${secrets.adminUsername}`,
    `ROOT_ADMIN_PASSWORD=${secrets.adminPassword}`,
    '',
    `POSTGRES_PORT=${ports.postgres}`,
    `POSTGREST_PORT=${ports.postgrest}`,
    `APP_PORT=${ports.app}`,
    `AUTH_PORT=${ports.auth}`,
    `DENO_PORT=${ports.deno}`,
    '',
    // Has to match the URL browsers actually use, or the dashboard calls the
    // wrong origin. Behind a reverse proxy on a server that is the public
    // https:// address, not localhost.
    `API_BASE_URL=${apiUrl}`,
    `VITE_API_BASE_URL=${apiUrl}`,
    '',
    `INSFORGE_DEPLOYMENT_METHOD=${publicUrl ? 'cli-selfhost' : 'cli-local'}`,
    '',
    // Canonical names, always written so readSecrets() can reconstruct the full
    // set. Without these a restart would fail to read the file back, regenerate
    // every secret, and rotate the API key out from under the app's .env.local.
    `INSFORGE_STORE_ACCESS_KEY=${secrets.storeAccessKey}`,
    `INSFORGE_STORE_SECRET_KEY=${secrets.storeSecretKey}`,
  ];

  if (stackTag) {
    lines.push('', `INSFORGE_STACK_TAG=${stackTag}`);
  }

  // Aliases under the names each storage overlay actually reads.
  if (storage === 'minio') {
    lines.push(
      '',
      `MINIO_ROOT_USER=${secrets.storeAccessKey}`,
      `MINIO_ROOT_PASSWORD=${secrets.storeSecretKey}`,
    );
  } else if (storage === 'rustfs') {
    lines.push(
      '',
      `RUSTFS_ACCESS_KEY=${secrets.storeAccessKey}`,
      `RUSTFS_SECRET_KEY=${secrets.storeSecretKey}`,
    );
  }

  return `${lines.join('\n')}\n`;
}

export function writeEnvFile(input: EnvFileInput, cwd?: string): void {
  // Create the directory and its .gitignore first: this file holds the
  // superadmin key and must never exist in a committable state, not even
  // between two statements.
  ensureLocalDir(cwd);
  ensureLocalGitignore(cwd);
  writeFileSync(localEnvFile(cwd), renderEnvFile(input), { mode: 0o600 });
}
