import { existsSync, readFileSync, writeFileSync, unlinkSync, renameSync } from 'node:fs';
import { join } from 'node:path';
import { execSync, spawn } from 'node:child_process';
import type { Command } from 'commander';
import { ossFetch } from '../../lib/api/oss.js';
import { requireAuth } from '../../lib/credentials.js';
import { handleError, getRootOpts, CLIError } from '../../lib/errors.js';
import { outputJson, outputSuccess, outputInfo } from '../../lib/output.js';
import { reportCliUsage } from '../../lib/skills.js';


interface FlyTomlConfig {
  internalPort?: number;
  memory?: string;
  cpuKind?: string;
  cpus?: number;
  region?: string;
}

function parseFlyToml(dir: string): FlyTomlConfig {
  const tomlPath = join(dir, 'fly.toml');
  if (!existsSync(tomlPath)) return {};

  const content = readFileSync(tomlPath, 'utf-8');
  const config: FlyTomlConfig = {};

  // Parse internal_port
  const portMatch = content.match(/internal_port\s*=\s*(\d+)/);
  if (portMatch) config.internalPort = Number(portMatch[1]);

  // Parse region
  const regionMatch = content.match(/primary_region\s*=\s*'([^']+)'/);
  if (regionMatch) config.region = regionMatch[1];

  // Parse vm settings
  const memoryMatch = content.match(/memory\s*=\s*'(\d+)/);
  if (memoryMatch) config.memory = memoryMatch[1];

  const cpuKindMatch = content.match(/cpu_kind\s*=\s*'([^']+)'/);
  if (cpuKindMatch) config.cpuKind = cpuKindMatch[1];

  const cpusMatch = content.match(/cpus\s*=\s*(\d+)/);
  if (cpusMatch) config.cpus = Number(cpusMatch[1]);

  return config;
}

function memoryToCpuTier(cpuKind?: string, cpus?: number): string | undefined {
  if (!cpuKind) return undefined;
  const kind = cpuKind === 'performance' ? 'performance' : 'shared';
  const count = cpus ?? 1;
  return `${kind}-${count}x`;
}

function generateFlyToml(appName: string, opts: {
  port: number;
  memory: number;
  cpu: string;
  region: string;
}): string {
  const cpuParts = opts.cpu.split('-');
  const cpuKind = cpuParts[0] ?? 'shared';
  const cpuCount = parseInt(cpuParts[1] ?? '1', 10);

  return `# Auto-generated by InsForge CLI
app = '${appName}'
primary_region = '${opts.region}'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = ${opts.port}
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '${opts.memory}mb'
  cpu_kind = '${cpuKind}'
  cpus = ${cpuCount}
`;
}

function checkFlyctl(): void {
  try {
    execSync('flyctl version', { stdio: 'pipe' });
  } catch {
    throw new CLIError(
      'flyctl is not installed.\n' +
      'Install it with: curl -L https://fly.io/install.sh | sh\n' +
      'Or: brew install flyctl',
    );
  }
}

async function getFlyToken(serviceId: string): Promise<string> {
  // Self-hosters with their own Fly account can still use their token.
  // Cloud-managed users get a short-lived scoped token from the OSS
  // backend (which proxies to the cloud, which mints it via Fly).
  // Either way, the user doesn't have to manage Fly credentials manually.
  const envToken = process.env.FLY_API_TOKEN;
  if (envToken) return envToken;

  try {
    const res = await ossFetch(
      `/api/compute/services/${encodeURIComponent(serviceId)}/deploy-token`,
      { method: 'POST' },
    );
    const body = (await res.json()) as { token?: string; expirySeconds?: number };
    if (!body.token) {
      throw new CLIError('OSS returned an empty deploy-token response');
    }
    return body.token;
  } catch (err) {
    if (err instanceof CLIError) throw err;
    throw new CLIError(
      'Could not fetch a Fly deploy token from your InsForge backend.\n' +
        'Either:\n' +
        '  - Set FLY_API_TOKEN with your own Fly token (self-hosted Fly account), or\n' +
        '  - Make sure your InsForge backend is updated to a version that supports cloud-managed compute.\n' +
        `Underlying error: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

export function registerComputeDeployCommand(computeCmd: Command): void {
  computeCmd
    .command('deploy [directory]')
    .description('Build and deploy a Dockerfile as a compute service')
    .requiredOption('--name <name>', 'Service name')
    .option('--port <port>', 'Container port')
    .option('--cpu <tier>', 'CPU tier (shared-1x, shared-2x, performance-1x, etc.)')
    .option('--memory <mb>', 'Memory in MB (256, 512, 1024, 2048, 4096, 8192)')
    .option('--region <region>', 'Fly.io region')
    .option('--env <json>', 'Environment variables as JSON object')
    .action(async (directory: string | undefined, opts, cmd) => {
      const { json } = getRootOpts(cmd);
      try {
        await requireAuth();
        checkFlyctl();
        // NOTE: flyToken is fetched AFTER service creation below so we know
        // the serviceId. Cloud-managed users get a short-lived scoped token
        // from OSS; self-hosters still use FLY_API_TOKEN env var directly.

        const dir = directory ?? process.cwd();
        const dockerfilePath = join(dir, 'Dockerfile');

        if (!existsSync(dockerfilePath)) {
          throw new CLIError(`No Dockerfile found in ${dir}`);
        }

        // Parse existing fly.toml for defaults
        const flyTomlDefaults = parseFlyToml(dir);

        const port = Number(opts.port) || flyTomlDefaults.internalPort || 8080;
        const cpu = opts.cpu || memoryToCpuTier(flyTomlDefaults.cpuKind, flyTomlDefaults.cpus) || 'shared-1x';
        const memory = Number(opts.memory) || Number(flyTomlDefaults.memory) || 512;
        const region = opts.region || flyTomlDefaults.region || 'iad';

        let envVars: Record<string, string> | undefined;
        if (opts.env) {
          try {
            envVars = JSON.parse(opts.env);
          } catch {
            throw new CLIError('Invalid JSON for --env');
          }
        }

        // Step 1: Check if service already exists
        if (!json) outputInfo(`Checking for existing service "${opts.name}"...`);

        const listRes = await ossFetch('/api/compute/services');
        const services = (await listRes.json()) as Record<string, unknown>[];
        const existing = services.find((s) => s.name === opts.name);

        let serviceId: string;
        let flyAppId: string;

        if (existing) {
          serviceId = existing.id as string;
          flyAppId = existing.flyAppId as string;
          if (!json) outputInfo(`Found existing service, redeploying...`);
        } else {
          // Step 2: Create service (app only, no machine)
          if (!json) outputInfo(`Creating service "${opts.name}"...`);

          const body: Record<string, unknown> = {
            name: opts.name,
            imageUrl: 'dockerfile',
            port,
            cpu,
            memory,
            region,
          };
          if (envVars) body.envVars = envVars;

          const deployRes = await ossFetch('/api/compute/services/deploy', {
            method: 'POST',
            body: JSON.stringify(body),
          });
          const service = (await deployRes.json()) as Record<string, unknown>;
          serviceId = service.id as string;
          flyAppId = service.flyAppId as string;
        }

        // Now that we have serviceId, fetch the deploy token (cloud mints
        // a scoped one if no FLY_API_TOKEN env var is set).
        const flyToken = await getFlyToken(serviceId);

        // Step 3: Generate fly.toml
        const existingTomlPath = join(dir, 'fly.toml');
        const backupTomlPath = join(dir, 'fly.toml.insforge-backup');
        let hadExistingToml = false;

        if (existsSync(existingTomlPath)) {
          hadExistingToml = true;
          renameSync(existingTomlPath, backupTomlPath);
        }

        const tomlContent = generateFlyToml(flyAppId, { port, memory, cpu, region });
        writeFileSync(existingTomlPath, tomlContent);

        try {
          // Step 4: Run flyctl deploy
          if (!json) outputInfo('Building and deploying (this may take a few minutes)...');

          await new Promise<void>((resolve, reject) => {
            const child = spawn(
              'flyctl',
              ['deploy', '--remote-only', '--app', flyAppId, '--access-token', flyToken, '--yes'],
              { cwd: dir, stdio: json ? 'pipe' : 'inherit' },
            );
            child.on('close', (code) => {
              if (code === 0) resolve();
              else reject(new CLIError(`flyctl deploy failed with exit code ${code}`));
            });
            child.on('error', (err) => reject(new CLIError(`flyctl deploy error: ${err.message}`)));
          });

          // Step 5: Sync machine info
          if (!json) outputInfo('Syncing deployment info...');

          const syncRes = await ossFetch(
            `/api/compute/services/${encodeURIComponent(serviceId)}/sync`,
            { method: 'PATCH' },
          );
          const synced = (await syncRes.json()) as Record<string, unknown>;

          if (json) {
            outputJson(synced);
          } else {
            outputSuccess(`Service "${synced.name}" deployed [${synced.status}]`);
            if (synced.endpointUrl) {
              console.log(`  Endpoint: ${synced.endpointUrl}`);
            }
          }

          await reportCliUsage('cli.compute.deploy', true);
        } finally {
          // Restore original fly.toml
          try {
            unlinkSync(existingTomlPath);
            if (hadExistingToml) {
              renameSync(backupTomlPath, existingTomlPath);
            }
          } catch {
            // Cleanup failure should not mask the real deploy error
          }
        }
      } catch (err) {
        await reportCliUsage('cli.compute.deploy', false);
        handleError(err, json);
      }
    });
}
