/**
 * Localhost human-in-the-loop approval surface.
 *
 * Spins up a single-use HTTP server, opens the approver's browser to a card
 * that explains the operation in human-readable terms, and BLOCKS the CLI
 * until a human clicks Approve or Deny (or the timeout elapses).
 *
 * Fail-closed: any error starting the server, and any timeout, resolves to
 * `denied` — the dangerous command never runs unless a human said yes.
 */

import { createServer } from 'node:http';
import type { AddressInfo } from 'node:net';
import open from 'open';
import type { Brief } from './brief.js';

export type ApprovalResult = 'approved' | 'denied' | 'timeout';

const TIMEOUT_MS = 120_000;

const SEVERITY_COLOR: Record<string, string> = {
  safe: '#16a34a',
  high: '#d97706',
  critical: '#dc2626',
};

function esc(s: string): string {
  return s.replace(/[&<>"']/g, (c) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] as string),
  );
}

function renderPage(brief: Brief): string {
  const color = SEVERITY_COLOR[brief.severity] ?? '#dc2626';
  const risks = brief.risks.map((r) => `<li>${esc(r)}</li>`).join('');
  return `<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>InsForge — Human approval required</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 15px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    margin: 0; background: #0b0d12; color: #e7e9ee; display: flex; min-height: 100vh;
    align-items: center; justify-content: center; padding: 24px; }
  .card { width: 100%; max-width: 620px; background: #14171f; border: 1px solid #232733;
    border-radius: 14px; overflow: hidden; box-shadow: 0 20px 60px rgba(0,0,0,.5); }
  .bar { height: 5px; background: ${color}; }
  .pad { padding: 24px 26px; }
  .tag { display: inline-block; font-size: 11px; font-weight: 700; letter-spacing: .08em;
    text-transform: uppercase; color: #fff; background: ${color}; padding: 4px 9px;
    border-radius: 999px; }
  h1 { font-size: 21px; margin: 14px 0 4px; }
  .sub { color: #8b93a7; font-size: 13px; margin-bottom: 18px; }
  .cmd { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 13px;
    background: #0b0d12; border: 1px solid #232733; border-radius: 8px; padding: 11px 13px;
    color: #d7dbe6; white-space: pre-wrap; word-break: break-word; margin-bottom: 18px; }
  section { margin: 14px 0; }
  .lbl { font-size: 11px; font-weight: 700; letter-spacing: .07em; text-transform: uppercase;
    color: #8b93a7; margin-bottom: 4px; }
  ul { margin: 6px 0 0; padding-left: 20px; }
  li { margin: 3px 0; }
  .rec { background: #0b0d12; border-left: 3px solid ${color}; border-radius: 6px;
    padding: 10px 13px; }
  .row { display: flex; gap: 12px; margin-top: 22px; }
  button { flex: 1; font-size: 15px; font-weight: 600; padding: 13px; border-radius: 9px;
    border: 1px solid transparent; cursor: pointer; }
  .deny { background: #1c2030; color: #e7e9ee; border-color: #2c3243; }
  .deny:hover { background: #232838; }
  .approve { background: ${color}; color: #fff; }
  .approve:hover { filter: brightness(1.08); }
  .done { text-align: center; padding: 40px 26px; }
  .foot { font-size: 11px; color: #5b6276; margin-top: 16px; text-align: center; }
</style></head>
<body>
  <div class="card" id="card">
    <div class="bar"></div>
    <div class="pad">
      <span class="tag">${esc(brief.severity)} · human approval required</span>
      <h1>${esc(brief.title)}</h1>
      <div class="sub">An automated agent is requesting to run a destructive InsForge operation.</div>
      <div class="cmd">$ ${esc(brief.command)}</div>

      <section><div class="lbl">What will happen</div><div>${esc(brief.whatHappens)}</div></section>
      <section><div class="lbl">Blast radius</div><div>${esc(brief.blastRadius)}</div></section>
      <section><div class="lbl">Risks</div><ul>${risks}</ul></section>
      <section><div class="lbl">What the agent is trying to do</div><div>${esc(brief.intent)}</div></section>
      <section><div class="lbl">Recommendation</div><div class="rec">${esc(brief.recommendation)}</div></section>

      <div class="row">
        <button class="deny" onclick="decide('deny')">Deny</button>
        <button class="approve" onclick="decide('approve')">Approve &amp; run</button>
      </div>
      <div class="foot">${brief.enriched ? 'Explanation generated by Claude' : 'Deterministic explanation'} · this window blocks the CLI until you choose</div>
    </div>
  </div>
<script>
  function decide(d) {
    fetch('/decision?d=' + d, { method: 'POST' }).then(function () {
      document.getElementById('card').innerHTML =
        '<div class="bar"></div><div class="done"><h1>' +
        (d === 'approve' ? 'Approved — running now.' : 'Denied — nothing ran.') +
        '</h1><div class="sub">You can close this window.</div></div>';
    });
  }
</script>
</body></html>`;
}

/**
 * Present the brief and block until a human decides.
 * Always resolves; defaults to 'denied' / 'timeout' on any failure.
 */
export function requestApproval(brief: Brief): Promise<ApprovalResult> {
  return new Promise((resolve) => {
    let settled = false;
    const finish = (r: ApprovalResult, server?: ReturnType<typeof createServer>) => {
      if (settled) return;
      settled = true;
      try { server?.close(); } catch { /* ignore */ }
      resolve(r);
    };

    const server = createServer((req, res) => {
      const url = req.url ?? '/';
      if (req.method === 'POST' && url.startsWith('/decision')) {
        const approved = url.includes('d=approve');
        res.writeHead(200, { 'content-type': 'text/plain' }).end('ok');
        finish(approved ? 'approved' : 'denied', server);
        return;
      }
      res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' }).end(renderPage(brief));
    });

    server.on('error', () => finish('denied', server)); // fail-closed

    server.listen(0, '127.0.0.1', () => {
      const { port } = server.address() as AddressInfo;
      const link = `http://127.0.0.1:${port}/`;
      // Always print the link so a human can approve even if no browser opened
      // (headless agents, remote sessions). This is the "works for all agents" path.
      process.stderr.write(`\n  🛑 Human approval required: ${link}\n\n`);
      // INSFORGE_GUARD_OPEN=0 prints the link only (headless servers, no focus steal).
      if (process.env.INSFORGE_GUARD_OPEN !== '0') {
        open(link).catch(() => { /* link already printed above */ });
      }
    });

    setTimeout(() => finish('timeout', server), TIMEOUT_MS);
  });
}
